---
## Install Vagrant Package
- name: Load tasks based on the OS type.
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

## Install Vagrant Plug-Ins; configure Vagrant
- import_tasks: vagrant-plugins.yml
- import_tasks: per-user.yml

## Other tasks relevant to the entire system
- import_tasks: global.yml
