---
- name: Configure sudo for vagrant-hostmanager plugin
  become: true
  copy:
    src: sudoers_d_vagrant_hostmanager
    dest: /etc/sudoers.d/vagrant_hostmanager
    owner: root
    group: wheel
    mode: 0644
