---
- name: Get list of installed Vagrant plugins
  command: "{{ vagrant_exe }} plugin list"
  register: installed_plugins
  changed_when: false

- name: Install Vagrant Plugins
  command: "{{ vagrant_exe }} plugin install {{ plugin }}"
  when: not installed_plugins.stdout | regex_search('^' ~ plugin ~ ' ', multiline=True)
  with_items: "{{ vagrant_plugins }}"
  loop_control:
    loop_var: plugin
    label: "{{ plugin }}"

- name: Install Vagrant plugins requiring a license
  block:
    - name: Create temporary directory to decrypt license file(s)
      tempfile:
        state: directory
        suffix: licenses
      register: tmpdir
      changed_when: false

    - name: Copy license file(s) for installation and (maybe) decryption
      copy:
        src: "{{ plugin.licfile }}"
        dest: "{{ tmpdir.path + '/' + plugin.licfile }}"
      when: not installed_plugins.stdout | regex_search('^' ~ plugin.name ~ ' ', multiline=True)
      loop: "{{ vagrant_plugins_licensed }}"
      loop_control:
        loop_var: plugin
        label: "{{ plugin.licfile }}"

    - name: Install Vagrant Plugins
      command: "{{ vagrant_exe }} plugin install {{ plugin.name }}"
      when: not installed_plugins.stdout | regex_search('^' ~ plugin.name ~ ' ', multiline=True)
      loop: "{{ vagrant_plugins_licensed }}"
      loop_control:
        loop_var: plugin
        label: "{{ plugin }}"

    ## Don't panic: installed_plugins was calculated *before* any plugins were installed by
    ## this run of this role.
    - name: Apply plugin license
      command: "{{ vagrant_exe }} plugin license {{ plugin.name }} {{ tmpdir.path + '/' + plugin.licfile }}"
      when: not installed_plugins.stdout | regex_search('^' ~ plugin.name ~ ' ', multiline=True)
      loop: "{{ vagrant_plugins_licensed }}"
      loop_control:
        loop_var: plugin
        label: "{{ plugin }}"

  always:
    - name: Remove local copy of license files
      file:
        path: "{{ tmpdir.path }}"
        state: absent
      changed_when: false
