---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: vmware_desktop
lint:
  name: yamllint
platforms:
  - name: macos-mojave
    box: msl/macos_mojave_10.14
    memory: 2048
    cpus: 2
    config_options:
      synced_folder: False
  - name: centos-7
    box: centos/7
    config_options:
      synced_folder: False
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../inventory/group_vars
verifier:
  name: testinfra
  lint:
    name: flake8
