---
dependency:
  name: galaxy

driver:
  name: vagrant

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: macos
    box: macinbox
  - name: centos-7
    box: centos/7

provisioner:
  name: ansible
  env:
    ANSIBLE_VAULT_PASSWORD_FILE: ${HOME}/.vault-password

verifier:
  name: ansible
